<?php
namespace App\Services\Import;
use App\Models\ApplicantApplication; use App\Services\Import\Concerns\ResolvesImportRelations; use Illuminate\Database\Eloquent\Model;
class AdmissionImportHandler extends AbstractImportHandler { use ResolvesImportRelations;
 public function type(): string { return 'applicants'; } public function label(): string { return 'Абитуриенты'; } public function modelClass(): string { return ApplicantApplication::class; } public function keyFields(): array { return ['email']; }
 public function fields(): array { return ['last_name'=>['label'=>'Фамилия','required'=>true,'aliases'=>['фамилия','last_name']],'first_name'=>['label'=>'Имя','required'=>true,'aliases'=>['имя','first_name']],'middle_name'=>['label'=>'Отчество','required'=>false,'aliases'=>['отчество','middle_name']],'education_program_id'=>['label'=>'ID программы','required'=>false,'aliases'=>['education_program_id']],'education_program_name'=>['label'=>'Программа','required'=>false,'aliases'=>['программа','образовательная программа','education_program']],'birth_date'=>['label'=>'Дата рождения','required'=>false,'aliases'=>['дата рождения','birth_date']],'phone'=>['label'=>'Телефон','required'=>false,'aliases'=>['телефон','phone']],'email'=>['label'=>'Email','required'=>false,'aliases'=>['email','почта','e-mail']],'education_base'=>['label'=>'База','required'=>false,'aliases'=>['база','education_base']],'status'=>['label'=>'Статус','required'=>false,'aliases'=>['статус','status']],'submitted_at'=>['label'=>'Дата подачи','required'=>false,'aliases'=>['дата подачи','submitted_at']],'comment'=>['label'=>'Комментарий','required'=>false,'aliases'=>['комментарий','comment']]]; }
 public function templateHeaders(): array { return ['Фамилия','Имя','Отчество','Образовательная программа','Дата рождения','Телефон','Email','База','Статус','Дата подачи','Комментарий']; } public function templateExample(): array { return ['Смирнова','Алина','Олеговна','Фортепиано','03.04.2010','+79990000020','applicant@example.test','9 классов','new','20.06.2026','Оригиналы документов ожидаются']; }
 public function prepare(array $data): array { $data['education_program_id']=$this->resolveProgramId($data['education_program_id']??null,$data['education_program_name']??null); $data['birth_date']=$this->normalizeDate($data['birth_date']??null); $data['submitted_at']=$this->normalizeDate($data['submitted_at']??null) ?: now()->toDateString(); $data['education_base']=$this->educationBase($data['education_base']??null); $data['status']=$this->applicantStatus($data['status']??null); return $data; }
 public function rules(): array { return ['education_program_id'=>['required','integer','exists:education_programs,id'],'last_name'=>['required','string','max:255'],'first_name'=>['required','string','max:255'],'middle_name'=>['nullable','string','max:255'],'birth_date'=>['nullable','date'],'phone'=>['nullable','string','max:50'],'email'=>['nullable','email','max:255'],'education_base'=>['required','in:after_9,after_11'],'status'=>['required','in:new,accepted,needs_clarification,rejected,enrolled'],'submitted_at'=>['required','date'],'comment'=>['nullable','string','max:5000']]; }
 public function findExisting(array $data): ?Model { return !empty($data['email']) ? ApplicantApplication::query()->legacy()->where('email',$data['email'])->first() : null; } protected function virtualFields(): array { return ['education_program_name']; }
 private function applicantStatus(?string $value): string { return match(mb_strtolower(trim((string)$value))) { 'принято','accepted'=>'accepted','уточнение','needs_clarification','неполный комплект'=>'needs_clarification','отклонено','rejected'=>'rejected','зачислен','enrolled'=>'enrolled', default=>'new' }; }
 private function educationBase(?string $value): string { $value=mb_strtolower(trim((string)$value)); return str_contains($value,'11') || $value === 'after_11' ? 'after_11' : 'after_9'; }
}
