<?php
namespace App\Services\Import;
use App\Models\Curriculum; use App\Models\CurriculumItem; use App\Services\AutoCodeService; use App\Services\Import\Concerns\ResolvesImportRelations; use Illuminate\Database\Eloquent\Model; use RuntimeException;
class CurriculumImportHandler extends AbstractImportHandler { use ResolvesImportRelations; public function __construct(private readonly AutoCodeService $autoCodeService) {}
 public function type(): string { return 'curricula'; } public function label(): string { return 'Учебные планы'; } public function modelClass(): string { return Curriculum::class; } public function keyFields(): array { return ['curriculum_code']; }
 public function fields(): array { return ['curriculum_code'=>['label'=>'Код учебного плана','required'=>false,'aliases'=>['код учебного плана','код плана','curriculum_code','code']],'curriculum_name'=>['label'=>'Учебный план','required'=>true,'aliases'=>['учебный план','название плана','curriculum_name','name']],'education_program_id'=>['label'=>'ID программы','required'=>false,'aliases'=>['education_program_id','id программы']],'education_program_name'=>['label'=>'Образовательная программа','required'=>false,'aliases'=>['образовательная программа','программа','education_program_name','program_name']],'year_start'=>['label'=>'Год начала','required'=>true,'aliases'=>['год начала','год набора','year_start']],'status'=>['label'=>'Статус','required'=>false,'aliases'=>['статус','status']],'description'=>['label'=>'Описание','required'=>false,'aliases'=>['описание','description']],'subject_id'=>['label'=>'ID дисциплины','required'=>false,'aliases'=>['subject_id','id дисциплины']],'subject_code'=>['label'=>'Код дисциплины','required'=>false,'aliases'=>['код дисциплины','subject_code']],'subject_name'=>['label'=>'Дисциплина','required'=>false,'aliases'=>['дисциплина','subject_name']],'course'=>['label'=>'Курс','required'=>true,'aliases'=>['курс','course']],'semester'=>['label'=>'Семестр','required'=>true,'aliases'=>['семестр','semester']],'hours_total'=>['label'=>'Часы','required'=>true,'aliases'=>['часы','hours_total','hours']],'control_form'=>['label'=>'Форма контроля','required'=>false,'aliases'=>['форма контроля','control_form']],'sort_order'=>['label'=>'Порядок','required'=>false,'aliases'=>['порядок','sort_order']]]; }
 public function templateHeaders(): array { return ['Код учебного плана','Учебный план','Образовательная программа','Год начала','Статус','Дисциплина','Код дисциплины','Курс','Семестр','Часы','Форма контроля','Порядок']; } public function templateExample(): array { return ['УП-ФО-2026','Учебный план Фортепиано 2026','Фортепиано','2026','draft','Специальность','SPEC-001','1','1','144','Экзамен','10']; }
 public function prepare(array $data): array { $data['education_program_id']=$this->resolveProgramId($data['education_program_id']??null,$data['education_program_name']??null); $data['subject_id']=$this->resolveSubjectId($data['subject_id']??null,$data['subject_code']??null,$data['subject_name']??null); $data['curriculum_code']=$data['curriculum_code'] ?: $this->autoCodeService->curriculumCode($data['curriculum_name']??null); $data['status']=$data['status'] ?: 'draft'; $data['sort_order']=$data['sort_order'] ?: 0; return $data; }
 public function rules(): array { return ['curriculum_code'=>['nullable','string','max:100'],'curriculum_name'=>['required','string','max:255'],'education_program_id'=>['required','integer','exists:education_programs,id'],'year_start'=>['required','integer','min:2000','max:2100'],'status'=>['nullable','string','max:50'],'description'=>['nullable','string'],'subject_id'=>['required','integer','exists:subjects,id'],'course'=>['required','integer','min:1','max:6'],'semester'=>['required','integer','min:1','max:12'],'hours_total'=>['required','integer','min:0','max:5000'],'control_form'=>['nullable','string','max:255'],'sort_order'=>['nullable','integer','min:0','max:65535']]; }
 public function findExisting(array $data): ?Model { return Curriculum::where('code',$data['curriculum_code']??null)->first(); }
 public function import(array $data,string $mode): string { $curriculum=Curriculum::where('code',$data['curriculum_code'])->first() ?: Curriculum::where('education_program_id',$data['education_program_id'])->where('name',$data['curriculum_name'])->where('year_start',$data['year_start'])->first(); if($mode===self::MODE_UPDATE && !$curriculum){return 'skipped';} $curriculumPayload=['code'=>$data['curriculum_code'],'education_program_id'=>$data['education_program_id'],'name'=>$data['curriculum_name'],'year_start'=>$data['year_start'],'status'=>$data['status'] ?: 'draft','description'=>$data['description']??null]; $curriculum=$curriculum ? tap($curriculum)->update($curriculumPayload) : Curriculum::create($curriculumPayload); $item=CurriculumItem::where('curriculum_id',$curriculum->id)->where('subject_id',$data['subject_id'])->where('course',$data['course'])->where('semester',$data['semester'])->first(); if($item){ if($mode===self::MODE_SKIP_DUPLICATES){return 'skipped';} if($mode===self::MODE_CREATE){throw new RuntimeException('Строка учебного плана уже существует.');}} $payload=['curriculum_id'=>$curriculum->id,'subject_id'=>$data['subject_id'],'course'=>$data['course'],'semester'=>$data['semester'],'hours_total'=>$data['hours_total'],'control_form'=>$data['control_form']??null,'sort_order'=>$data['sort_order']??0]; if($item){$item->update($payload); return 'updated';} CurriculumItem::create($payload); return 'created'; }
}
