<?php
namespace App\Services\Import;
use App\DTO\ScheduleLessonData; use App\Models\ScheduleLesson; use App\Services\Import\Concerns\ResolvesImportRelations; use App\Services\ScheduleLessonService; use Illuminate\Database\Eloquent\Model; use RuntimeException;
class ScheduleImportHandler extends AbstractImportHandler { use ResolvesImportRelations; public function __construct(private readonly ScheduleLessonService $scheduleLessonService) {}
 public function type(): string { return 'schedule'; } public function label(): string { return 'Расписание'; } public function modelClass(): string { return ScheduleLesson::class; } public function keyFields(): array { return ['lesson_date','starts_at','group_id','subject_id','teacher_id']; }
 public function fields(): array { return ['lesson_date'=>['label'=>'Дата','required'=>true,'aliases'=>['дата','lesson_date']],'starts_at'=>['label'=>'Время начала','required'=>true,'aliases'=>['время начала','starts_at','начало']],'ends_at'=>['label'=>'Время окончания','required'=>true,'aliases'=>['время окончания','ends_at','окончание']],'group_id'=>['label'=>'ID группы','required'=>false,'aliases'=>['group_id','id группы']],'group_name'=>['label'=>'Группа','required'=>false,'aliases'=>['группа','group','group_name']],'teacher_id'=>['label'=>'ID преподавателя','required'=>false,'aliases'=>['teacher_id','id преподавателя']],'teacher_name'=>['label'=>'Преподаватель','required'=>false,'aliases'=>['преподаватель','teacher','teacher_name']],'subject_id'=>['label'=>'ID дисциплины','required'=>false,'aliases'=>['subject_id','id дисциплины']],'subject_code'=>['label'=>'Код дисциплины','required'=>false,'aliases'=>['код дисциплины','subject_code']],'subject_name'=>['label'=>'Дисциплина','required'=>false,'aliases'=>['дисциплина','subject_name']],'classroom_id'=>['label'=>'ID аудитории','required'=>false,'aliases'=>['classroom_id','id аудитории']],'classroom_number'=>['label'=>'Аудитория','required'=>false,'aliases'=>['аудитория','classroom','classroom_number']],'classroom_building'=>['label'=>'Корпус','required'=>false,'aliases'=>['корпус','building','classroom_building']],'lesson_type'=>['label'=>'Тип занятия','required'=>false,'aliases'=>['тип занятия','lesson_type']],'topic'=>['label'=>'Тема','required'=>false,'aliases'=>['тема','topic']]]; }
 public function templateHeaders(): array { return ['Дата','Время начала','Время окончания','Группа','Преподаватель','Дисциплина','Код дисциплины','Аудитория','Корпус','Тип занятия','Тема']; } public function templateExample(): array { return ['01.09.2026','09:00','10:30','ИСП-101','Петрова Анна Викторовна','Специальность','SPEC-001','201','Главный корпус','Практическое','Вводное занятие']; }
 public function prepare(array $data): array { $data['lesson_date']=$this->normalizeDate($data['lesson_date']??null); $data['starts_at']=$this->normalizeTime($data['starts_at']??null); $data['ends_at']=$this->normalizeTime($data['ends_at']??null); $data['group_id']=$this->resolveGroupId($data['group_id']??null,$data['group_name']??null); $data['teacher_id']=$this->resolveTeacherId($data['teacher_id']??null,$data['teacher_name']??null); $data['subject_id']=$this->resolveSubjectId($data['subject_id']??null,$data['subject_code']??null,$data['subject_name']??null); $data['classroom_id']=$this->resolveClassroomId($data['classroom_id']??null,$data['classroom_number']??null,$data['classroom_building']??null); $data['lesson_type']=$data['lesson_type'] ?: 'lesson'; return $data; }
 public function rules(): array { return ['lesson_date'=>['required','date'],'starts_at'=>['required','date_format:H:i'],'ends_at'=>['required','date_format:H:i','after:starts_at'],'group_id'=>['required','integer','exists:groups,id'],'teacher_id'=>['required','integer','exists:teachers,id'],'subject_id'=>['required','integer','exists:subjects,id'],'classroom_id'=>['nullable','integer','exists:classrooms,id'],'lesson_type'=>['required','string','max:255'],'topic'=>['nullable','string','max:255']]; }
 public function findExisting(array $data): ?Model { return ScheduleLesson::where('lesson_date',$data['lesson_date']??null)->where('starts_at',$data['starts_at']??null)->where('group_id',$data['group_id']??null)->where('subject_id',$data['subject_id']??null)->where('teacher_id',$data['teacher_id']??null)->first(); }
 public function import(array $data,string $mode): string { $lesson=$this->findExisting($data); if($mode===self::MODE_UPDATE && !$lesson){return 'skipped';} if($lesson){ if($mode===self::MODE_SKIP_DUPLICATES){return 'skipped';} if($mode===self::MODE_CREATE){throw new RuntimeException('Занятие уже существует.');}} $lessonData=ScheduleLessonData::fromArray($this->schedulePayload($data)); if($lesson){$this->scheduleLessonService->update($lesson,$lessonData); return 'updated';} $this->scheduleLessonService->create($lessonData); return 'created'; }
 public function businessValidationErrors(array $data): array { return $this->scheduleConflictMessages($data,$this->findExisting($data)?->id); }
 private function schedulePayload(array $data): array { return ['group_id'=>$data['group_id'],'teacher_id'=>$data['teacher_id'],'subject_id'=>$data['subject_id'],'classroom_id'=>$data['classroom_id']??null,'lesson_date'=>$data['lesson_date'],'starts_at'=>$data['starts_at'],'ends_at'=>$data['ends_at'],'lesson_type'=>$data['lesson_type'] ?: 'lesson','topic'=>$data['topic']??null]; }
 private function scheduleConflictMessages(array $data,?int $ignoreLessonId=null): array { $errors=[]; if($this->scheduleHasConflict('group_id',(int)$data['group_id'],$data,$ignoreLessonId)){$errors['group_id'][]='Группа уже занята в это время.';} if($this->scheduleHasConflict('teacher_id',(int)$data['teacher_id'],$data,$ignoreLessonId)){$errors['teacher_id'][]='Преподаватель уже ведет занятие в это время.';} if(!empty($data['classroom_id']) && $this->scheduleHasConflict('classroom_id',(int)$data['classroom_id'],$data,$ignoreLessonId)){$errors['classroom_id'][]='Аудитория уже занята в это время.';} return $errors; }
 private function scheduleHasConflict(string $column,int $value,array $data,?int $ignoreLessonId): bool { return ScheduleLesson::query()->where($column,$value)->whereDate('lesson_date',$data['lesson_date'])->where('starts_at','<',$data['ends_at'])->where('ends_at','>',$data['starts_at'])->when($ignoreLessonId,fn($query)=>$query->whereKeyNot($ignoreLessonId))->exists(); }
}
