<?php
namespace App\Services\Import;
use App\Models\Student; use App\Services\Import\Concerns\ResolvesImportRelations; use Illuminate\Database\Eloquent\Model;
class StudentImportHandler extends AbstractImportHandler { use ResolvesImportRelations;
 public function type(): string { return 'students'; } public function label(): string { return 'Студенты'; } public function modelClass(): string { return Student::class; } public function keyFields(): array { return ['email']; }
 public function fields(): array { return ['last_name'=>['label'=>'Фамилия','required'=>true,'aliases'=>['фамилия','last_name']],'first_name'=>['label'=>'Имя','required'=>true,'aliases'=>['имя','first_name']],'middle_name'=>['label'=>'Отчество','required'=>false,'aliases'=>['отчество','middle_name']],'group_id'=>['label'=>'ID группы','required'=>false,'aliases'=>['group_id','id группы']],'group_name'=>['label'=>'Группа','required'=>false,'aliases'=>['группа','group','group_name']],'birth_date'=>['label'=>'Дата рождения','required'=>false,'aliases'=>['дата рождения','birth_date']],'phone'=>['label'=>'Телефон','required'=>false,'aliases'=>['телефон','phone']],'email'=>['label'=>'Email','required'=>false,'aliases'=>['email','почта','e-mail']],'status'=>['label'=>'Статус','required'=>false,'aliases'=>['статус','status']],'enrollment_date'=>['label'=>'Дата зачисления','required'=>false,'aliases'=>['дата зачисления','enrollment_date']]]; }
 public function templateHeaders(): array { return ['Фамилия','Имя','Отчество','Группа','Дата рождения','Телефон','Email','Статус','Дата зачисления']; } public function templateExample(): array { return ['Иванов','Дмитрий','Сергеевич','ИСП-101','12.05.2009','+79990000002','student@example.test','active','01.09.2026']; }
 public function prepare(array $data): array { $data['birth_date']=$this->normalizeDate($data['birth_date']??null); $data['enrollment_date']=$this->normalizeDate($data['enrollment_date']??null); $data['group_id']=$this->resolveGroupId($data['group_id']??null,$data['group_name']??null); $data['status']=$this->studentStatus($data['status']??null); return $data; }
 public function rules(): array { return ['group_id'=>['required','integer','exists:groups,id'],'last_name'=>['required','string','max:255'],'first_name'=>['required','string','max:255'],'middle_name'=>['nullable','string','max:255'],'birth_date'=>['nullable','date'],'phone'=>['nullable','string','max:50'],'email'=>['nullable','email','max:255'],'status'=>['required','in:active,academic_leave,graduated,expelled'],'enrollment_date'=>['nullable','date']]; }
 public function findExisting(array $data): ?Model { return !empty($data['email']) ? Student::where('email',$data['email'])->first() : null; } protected function virtualFields(): array { return ['group_name']; }
 private function studentStatus(?string $value): string { return match(mb_strtolower(trim((string)$value))) { 'академический отпуск','academic_leave'=>'academic_leave','выпускник','graduated'=>'graduated','отчислен','expelled'=>'expelled', default=>'active' }; }
}
