<?php

namespace App\Services\Import;

use App\Models\Student;
use App\Services\AccountProvisioningService;
use App\Services\Admissions\SnilsService;
use App\Services\Import\Concerns\ResolvesImportRelations;
use Illuminate\Database\Eloquent\Model;
use RuntimeException;

class StudentImportHandler extends AbstractImportHandler
{
    use ResolvesImportRelations;

    public function __construct(private readonly SnilsService $snils, private readonly ?AccountProvisioningService $accounts = null)
    {
    }

    public function type(): string { return 'students'; }
    public function label(): string { return 'Студенты'; }
    public function modelClass(): string { return Student::class; }
    public function keyFields(): array { return ['snils', 'email', 'last_name', 'first_name', 'birth_date']; }
    public function fields(): array { return ['last_name'=>['label'=>'Фамилия','required'=>true,'aliases'=>['фамилия','last_name']],'first_name'=>['label'=>'Имя','required'=>true,'aliases'=>['имя','first_name']],'middle_name'=>['label'=>'Отчество','required'=>false,'aliases'=>['отчество','middle_name']],'group_id'=>['label'=>'ID группы','required'=>false,'aliases'=>['group_id','id группы']],'group_name'=>['label'=>'Группа','required'=>false,'aliases'=>['группа','group','group_name']],'course'=>['label'=>'Курс','required'=>false,'aliases'=>['курс','номер курса','год обучения','course']],'specialty'=>['label'=>'Специальность','required'=>false,'aliases'=>['специальность','specialty']],'education_form'=>['label'=>'Форма обучения','required'=>false,'aliases'=>['форма обучения','очная/заочная','education_form']],'birth_date'=>['label'=>'Дата рождения','required'=>false,'aliases'=>['дата рождения','birth_date']],'phone'=>['label'=>'Телефон','required'=>false,'aliases'=>['телефон','phone']],'email'=>['label'=>'Email','required'=>false,'aliases'=>['email','почта','e-mail']],'snils'=>['label'=>'СНИЛС','required'=>false,'aliases'=>['снилс','snils']],'address'=>['label'=>'Адрес','required'=>false,'aliases'=>['адрес','домашний адрес','address']],'status'=>['label'=>'Статус','required'=>false,'aliases'=>['статус','status']],'enrollment_date'=>['label'=>'Дата зачисления','required'=>false,'aliases'=>['дата зачисления','enrollment_date']],'enrollment_order_number'=>['label'=>'Приказ о зачислении','required'=>false,'aliases'=>['приказ о зачислении','номер приказа','enrollment_order_number']],'enrollment_order_date'=>['label'=>'Дата приказа о зачислении','required'=>false,'aliases'=>['дата приказа о зачислении','enrollment_order_date']],'auto_account'=>['label'=>'Создать учетную запись','required'=>false,'aliases'=>['создать учетную запись','auto_account']]]; }
    public function templateHeaders(): array { return ['Фамилия','Имя','Отчество','Группа','Дата рождения','Телефон','Email','СНИЛС','Статус','Дата зачисления','Курс','Специальность','Форма обучения','Адрес','Приказ о зачислении','Дата приказа о зачислении','Создать учетную запись']; }
    public function templateExample(): array { return ['Иванов','Дмитрий','Сергеевич','ИСП-101','12.05.2009','+79990000002','student@example.test','','active','01.09.2026','1','Инструментальное исполнительство','Очная','г. Ставрополь, ул. Примерная, д. 1','91','15.08.2026','нет']; }
    public function prepare(array $data): array { $data['birth_date']=$this->normalizeDate($data['birth_date']??null); $data['enrollment_date']=$this->normalizeDate($data['enrollment_date']??null); $data['enrollment_order_date']=$this->normalizeDate($data['enrollment_order_date']??null); $data['snils']=preg_replace('/\D+/', '', (string) ($data['snils']??'')) ?: null; $data['group_id']=$this->resolveGroupId($data['group_id']??null,$data['group_name']??null); $data['status']=$this->studentStatus($data['status']??null); $data['auto_account']=$this->booleanValue($data['auto_account']??false); return $data; }
    public function rules(): array { return ['group_id'=>['required','integer','exists:groups,id'],'last_name'=>['required','string','max:255'],'first_name'=>['required','string','max:255'],'middle_name'=>['nullable','string','max:255'],'course'=>['nullable','integer','min:1','max:6'],'specialty'=>['nullable','string','max:255'],'education_form'=>['nullable','string','max:80'],'birth_date'=>['nullable','date'],'phone'=>['nullable','string','max:50'],'email'=>['nullable','email','max:255'],'snils'=>['nullable','string','max:32'],'address'=>['nullable','string','max:2000'],'status'=>['required','in:active,academic_leave,graduated,expelled'],'enrollment_date'=>['nullable','date'],'enrollment_order_number'=>['nullable','string','max:100'],'enrollment_order_date'=>['nullable','date'],'auto_account'=>['boolean']]; }
    public function findExisting(array $data): ?Model { $matches=collect(); if (!empty($data['snils'])) $matches=$matches->merge(Student::where('snils',$data['snils'])->get()); if (!empty($data['email'])) $matches=$matches->merge(Student::where('email',$data['email'])->get()); if (!empty($data['birth_date'])) $matches=$matches->merge(Student::where('last_name',$data['last_name'])->where('first_name',$data['first_name'])->where('birth_date',$data['birth_date'])->get()); if ($matches->isEmpty()) $matches=$matches->merge(Student::where('group_id',$data['group_id'])->where('last_name',$data['last_name'])->where('first_name',$data['first_name'])->where('middle_name',$data['middle_name'] ?? null)->get()); $matches=$matches->unique('id')->values(); if ($matches->count()>1) throw new RuntimeException('Найдено несколько совпадающих студентов. Уточните СНИЛС, email или дату рождения.'); return $matches->first(); }
    public function import(array $data, string $mode): string { $existing=$this->findExisting($data); if ($mode===self::MODE_UPDATE) { if (!$existing) return 'skipped'; $existing->update($this->payload($data,true)); return 'updated'; } if ($existing) { if ($mode===self::MODE_SKIP_DUPLICATES) return 'skipped'; throw new RuntimeException('Дубликат по ключевому полю.'); } $student=Student::create($this->payload($data)); if ($data['auto_account'] && $this->accounts) $this->accounts->provision($student); return 'created'; }
    public function businessValidationErrors(array $data): array { if (blank($data['snils'] ?? null)) return []; try { $this->snils->normalize($data['snils']); return []; } catch (\Illuminate\Validation\ValidationException $exception) { return ['snils' => $exception->errors()['snils'] ?? [$exception->getMessage()]]; } }
    protected function virtualFields(): array { return ['group_name','specialty','auto_account']; }
    private function studentStatus(?string $value): string { return match(mb_strtolower(trim((string)$value))) { 'академический отпуск','academic_leave'=>'academic_leave','выпускник','graduated'=>'graduated','отчислен','expelled'=>'expelled', default=>'active' }; }
}
