<?php
namespace App\Services\Import;
use App\Models\TeachingLoad; use App\Models\TeachingLoadItem; use App\Services\Import\Concerns\ResolvesImportRelations; use Illuminate\Database\Eloquent\Model; use RuntimeException;
class TeachingLoadImportHandler extends AbstractImportHandler { use ResolvesImportRelations;
 public function type(): string { return 'teaching-load'; } public function label(): string { return 'Нагрузка преподавателей'; } public function modelClass(): string { return TeachingLoad::class; } public function keyFields(): array { return ['academic_year','teacher_id']; }
 public function fields(): array { return ['academic_year'=>['label'=>'Учебный год','required'=>true,'aliases'=>['учебный год','academic_year']],'teacher_id'=>['label'=>'ID преподавателя','required'=>false,'aliases'=>['teacher_id','id преподавателя']],'teacher_name'=>['label'=>'Преподаватель','required'=>false,'aliases'=>['преподаватель','teacher','teacher_name']],'status'=>['label'=>'Статус','required'=>false,'aliases'=>['статус','status']],'description'=>['label'=>'Описание','required'=>false,'aliases'=>['описание','description']],'subject_id'=>['label'=>'ID дисциплины','required'=>false,'aliases'=>['subject_id','id дисциплины']],'subject_code'=>['label'=>'Код дисциплины','required'=>false,'aliases'=>['код дисциплины','subject_code']],'subject_name'=>['label'=>'Дисциплина','required'=>false,'aliases'=>['дисциплина','subject_name']],'group_id'=>['label'=>'ID группы','required'=>false,'aliases'=>['group_id','id группы']],'group_name'=>['label'=>'Группа','required'=>false,'aliases'=>['группа','group','group_name']],'semester'=>['label'=>'Семестр','required'=>true,'aliases'=>['семестр','semester']],'hours_total'=>['label'=>'Часы','required'=>true,'aliases'=>['часы','hours_total','hours']],'load_type'=>['label'=>'Тип нагрузки','required'=>false,'aliases'=>['тип нагрузки','load_type']],'sort_order'=>['label'=>'Порядок','required'=>false,'aliases'=>['порядок','sort_order']]]; }
 public function templateHeaders(): array { return ['Учебный год','Преподаватель','Статус','Дисциплина','Код дисциплины','Группа','Семестр','Часы','Тип нагрузки','Порядок']; } public function templateExample(): array { return ['2026/2027','Петрова Анна Викторовна','draft','Специальность','SPEC-001','ИСП-101','1','72','Аудиторная','10']; }
 public function prepare(array $data): array { $data['teacher_id']=$this->resolveTeacherId($data['teacher_id']??null,$data['teacher_name']??null); $data['subject_id']=$this->resolveSubjectId($data['subject_id']??null,$data['subject_code']??null,$data['subject_name']??null); $data['group_id']=$this->resolveGroupId($data['group_id']??null,$data['group_name']??null); $data['status']=$data['status'] ?: 'draft'; $data['load_type']=$data['load_type'] ?: 'Аудиторная'; $data['sort_order']=$data['sort_order'] ?: 0; return $data; }
 public function rules(): array { return ['academic_year'=>['required','string','max:20'],'teacher_id'=>['required','integer','exists:teachers,id'],'status'=>['nullable','string','max:50'],'description'=>['nullable','string'],'subject_id'=>['required','integer','exists:subjects,id'],'group_id'=>['required','integer','exists:groups,id'],'semester'=>['required','integer','min:1','max:12'],'hours_total'=>['required','integer','min:0','max:5000'],'load_type'=>['required','string','max:255'],'sort_order'=>['nullable','integer','min:0','max:65535']]; }
 public function findExisting(array $data): ?Model { return TeachingLoad::where('academic_year',$data['academic_year']??null)->where('teacher_id',$data['teacher_id']??null)->first(); }
 public function import(array $data,string $mode): string { $load=TeachingLoad::where('academic_year',$data['academic_year'])->where('teacher_id',$data['teacher_id'])->first(); if($mode===self::MODE_UPDATE && !$load){return $this->skipped(self::SKIP_NOT_FOUND);} $loadPayload=['academic_year'=>$data['academic_year'],'teacher_id'=>$data['teacher_id'],'status'=>$data['status'] ?: 'draft','description'=>$data['description']??null]; $load=$load ? tap($load)->update($loadPayload) : TeachingLoad::create($loadPayload); $item=TeachingLoadItem::where('teaching_load_id',$load->id)->where('subject_id',$data['subject_id'])->where('group_id',$data['group_id'])->where('semester',$data['semester'])->where('load_type',$data['load_type'])->first(); if($item){ if($mode===self::MODE_SKIP_DUPLICATES){return $this->skipped(self::SKIP_DUPLICATE);} if($mode===self::MODE_CREATE){throw new RuntimeException('Строка нагрузки уже существует.');}} $payload=['teaching_load_id'=>$load->id,'subject_id'=>$data['subject_id'],'group_id'=>$data['group_id'],'semester'=>$data['semester'],'hours_total'=>$data['hours_total'],'load_type'=>$data['load_type'],'sort_order'=>$data['sort_order']??0]; if($item){$item->update($payload); return 'updated';} TeachingLoadItem::create($payload); return 'created'; }
}
