<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AccessGateController;
use App\Http\Controllers\Api\AccessReportController;
use App\Http\Controllers\Api\AdminRoleController;
use App\Http\Controllers\Api\AdminPermissionController;
use App\Http\Controllers\Api\AdminSettingController;
use App\Http\Controllers\Api\AuditLogController;
use App\Http\Controllers\Api\AdminUserController;
use App\Http\Controllers\Api\ApplicantApplicationController;
use App\Http\Controllers\Api\ApplicantDocumentController;
use App\Http\Controllers\Api\AdmissionBulkController;
use App\Http\Controllers\Api\GroupController;
use App\Http\Controllers\Api\MobileStudentController;
use App\Http\Controllers\Api\PersonController;
use App\Http\Controllers\Api\PersonPhotoController;
use App\Http\Controllers\Api\AttendanceController;
use App\Http\Controllers\Api\AttendanceAnalysisController;
use App\Http\Controllers\Api\ClassroomController;
use App\Http\Controllers\Api\CurriculumController;
use App\Http\Controllers\Api\DigitalIdentityController;
use App\Http\Controllers\Api\DemoDataController;
use App\Http\Controllers\Api\DashboardAnalyticsController;
use App\Http\Controllers\Api\DashboardLayoutController;
use App\Http\Controllers\Api\ExamController;
use App\Http\Controllers\Api\FrdoPackageController;
use App\Http\Controllers\Api\FisPackageController;
use App\Http\Controllers\Api\FisAdmissionsImportController;
use App\Http\Controllers\Api\EducationProgramController;
use App\Http\Controllers\Api\GradeController;
use App\Http\Controllers\Api\GraduateController;
use App\Http\Controllers\Api\StudentController;
use App\Http\Controllers\Api\StudentBulkController;
use App\Http\Controllers\Api\SubjectController;
use App\Http\Controllers\Api\ScheduleLessonController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\ReferenceCatalogController;
use App\Http\Controllers\Api\ReferenceItemController;
use App\Http\Controllers\Api\SpecialtyController;
use App\Http\Controllers\Api\TeacherController;
use App\Http\Controllers\Api\UniversalImportController;
use App\Http\Controllers\Api\TeachingLoadController;
use Illuminate\Support\Facades\Route;

Route::post('auth/login', [AuthController::class, 'login']);
Route::get('settings/public', [AdminSettingController::class, 'publicSettings']);
Route::get('public/specialties', [SpecialtyController::class, 'index']);
Route::get('public/education-programs', [EducationProgramController::class, 'index']);

Route::middleware('api.token')->group(function (): void {
    Route::get('auth/me', [AuthController::class, 'me']);
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::get('mobile/student', [MobileStudentController::class, 'show']);
    Route::get('dashboard/layouts', [DashboardLayoutController::class, 'index']);
    Route::post('dashboard/layouts', [DashboardLayoutController::class, 'store']);
    Route::post('dashboard/layouts/reset', [DashboardLayoutController::class, 'reset']);
    Route::put('dashboard/layouts/{dashboardLayout}', [DashboardLayoutController::class, 'update']);
    Route::delete('dashboard/layouts/{dashboardLayout}', [DashboardLayoutController::class, 'destroy']);
    Route::post('dashboard/layouts/{dashboardLayout}/activate', [DashboardLayoutController::class, 'activate']);


    Route::middleware('permission:people.view')->group(function (): void {
        Route::get('people', [PersonController::class, 'index']);
        Route::get('people/{person}', [PersonController::class, 'show']);
        Route::get('people/{person}/profiles', [PersonController::class, 'profiles']);
    });

    Route::middleware('permission:view_reports')->group(function (): void {
        Route::get('dashboard/analytics/executive', [DashboardAnalyticsController::class, 'executive']);
        Route::get('attendance/teachers/today', [AttendanceAnalysisController::class, 'teachersToday']);
        Route::get('attendance/students/today', [AttendanceAnalysisController::class, 'studentsToday']);
        Route::get('attendance/history', [AttendanceAnalysisController::class, 'history']);
        Route::get('attendance/person/{type}/{id}/summary', [AttendanceAnalysisController::class, 'personSummary']);
        Route::get('attendance/person/{type}/{id}/days', [AttendanceAnalysisController::class, 'personDays']);
    });

    Route::middleware('permission:manage_users')->group(function (): void {
        Route::get('admin/audit', [AuditLogController::class, 'index']);
        Route::get('admin/settings', [AdminSettingController::class, 'index']);
        Route::put('admin/settings', [AdminSettingController::class, 'update']);
        Route::get('admin/audit/{auditLog}', [AuditLogController::class, 'show']);
        Route::apiResource('admin/permissions', AdminPermissionController::class)->except(['show']);
        Route::post('admin/permissions/{permission}/roles', [AdminPermissionController::class, 'assignRoles']);
        Route::get('admin/permissions/roles/list', [AdminPermissionController::class, 'roles']);
        Route::apiResource('admin/roles', AdminRoleController::class)->except(['show']);
        Route::get('admin/users/roles', [AdminUserController::class, 'roles']);
        Route::get('admin/users/people', [AdminUserController::class, 'people']);
        Route::post('admin/users/{user}/roles', [AdminUserController::class, 'assignRoles']);
        Route::post('admin/users/{user}/block', [AdminUserController::class, 'block']);
        Route::post('admin/users/{user}/unblock', [AdminUserController::class, 'unblock']);
        Route::apiResource('admin/users', AdminUserController::class);
    });

    Route::middleware('permission:manage_dictionaries')->group(function (): void {
        Route::apiResource('admin/reference/catalogs', ReferenceCatalogController::class)->parameters(['catalogs' => 'catalog'])->except(['show']);
        Route::apiResource('admin/reference/items', ReferenceItemController::class)->parameters(['items' => 'item'])->except(['show']);
        Route::get('admin/import/config', [UniversalImportController::class, 'config']);
        Route::get('admin/import/history', [UniversalImportController::class, 'history']);
        Route::get('admin/import/templates/{dataType}.csv', [UniversalImportController::class, 'template']);
        Route::post('admin/import/fis-admissions/analyze', [FisAdmissionsImportController::class, 'analyze']);
        Route::post('admin/import/fis-admissions/dry-run', [FisAdmissionsImportController::class, 'dryRun']);
        Route::post('admin/import/fis-admissions/apply', [FisAdmissionsImportController::class, 'apply']);
        Route::get('admin/import/fis-admissions/jobs/{importJob}', [FisAdmissionsImportController::class, 'show']);
        Route::post('admin/import/preview', [UniversalImportController::class, 'preview']);
        Route::post('admin/import/{importJob}/validate', [UniversalImportController::class, 'validateJob']);
        Route::post('admin/import/{importJob}/confirm', [UniversalImportController::class, 'confirm']);
        Route::get('admin/demo-data', [DemoDataController::class, 'status']);
        Route::post('admin/demo-data/create', [DemoDataController::class, 'create']);
        Route::post('admin/demo-data/clear', [DemoDataController::class, 'clear']);
        Route::post('admin/demo-data/import', [DemoDataController::class, 'import']);
        Route::get('admin/demo-data/export', [DemoDataController::class, 'export']);
        Route::post('person-photos/{type}/{id}', [PersonPhotoController::class, 'store']);
        Route::delete('person-photos/{type}/{id}', [PersonPhotoController::class, 'destroy']);
        Route::get('classrooms/export', [ClassroomController::class, 'export']);
        Route::post('classrooms/import', [ClassroomController::class, 'import']);
        Route::apiResource('classrooms', ClassroomController::class);
        Route::get('access/events', [AccessGateController::class, 'events']);
        Route::post('access/scan', [AccessGateController::class, 'scan']);
        Route::get('access/reports/summary', [AccessReportController::class, 'summary']);
        Route::get('access/reports/events', [AccessReportController::class, 'events']);
        Route::get('digital-identities', [DigitalIdentityController::class, 'index']);
        Route::post('digital-identities/issue', [DigitalIdentityController::class, 'issue']);
        Route::post('digital-identities/{digitalIdentity}/revoke', [DigitalIdentityController::class, 'revoke']);
        Route::get('digital-identities/{digitalIdentity}/qr', [DigitalIdentityController::class, 'qr']);
        Route::get('admissions/{applicantApplication}/documents', [ApplicantDocumentController::class, 'index'])->middleware('permission:admissions.documents.view');
        Route::post('admissions/{applicantApplication}/documents/{type}/receive', [ApplicantDocumentController::class, 'receive'])->middleware('permission:admissions.documents.receive');
        Route::post('admissions/{applicantApplication}/documents/{type}/upload', [ApplicantDocumentController::class, 'upload'])->middleware('permission:admissions.documents.upload');
        Route::post('admissions/{applicantApplication}/documents/{document}/verify', [ApplicantDocumentController::class, 'verify'])->middleware('permission:admissions.documents.verify');
        Route::post('admissions/{applicantApplication}/documents/{document}/reject', [ApplicantDocumentController::class, 'reject'])->middleware('permission:admissions.documents.reject');
        Route::put('admissions/{applicantApplication}/documents/{document}', [ApplicantDocumentController::class, 'update'])->middleware('permission:admissions.documents.receive');
        Route::delete('admissions/{applicantApplication}/documents/{document}', [ApplicantDocumentController::class, 'destroy'])->middleware('permission:admissions.documents.delete');
        Route::get('admissions/{applicantApplication}/documents/{document}/files/{file}/download', [ApplicantDocumentController::class, 'download'])->middleware('permission:admissions.documents.download');
        Route::delete('admissions/{applicantApplication}/documents/{document}/files/{file}', [ApplicantDocumentController::class, 'destroyFile'])->middleware('permission:admissions.documents.delete');
        Route::get('admissions/stats', [ApplicantApplicationController::class, 'stats']);
        Route::get('applicant-applications/stats', [ApplicantApplicationController::class, 'stats']);
        Route::post('admissions/bulk/preview', [AdmissionBulkController::class, 'preview']);
        Route::post('admissions/bulk/apply', [AdmissionBulkController::class, 'apply']);
        Route::post('applicant-applications/bulk/preview', [AdmissionBulkController::class, 'preview']);
        Route::post('applicant-applications/bulk/apply', [AdmissionBulkController::class, 'apply']);
        Route::get('applicant-applications/export', [ApplicantApplicationController::class, 'export']);
        Route::post('applicant-applications/import', [ApplicantApplicationController::class, 'import']);
        Route::post('applicant-applications/{applicantApplication}/enroll', [ApplicantApplicationController::class, 'enroll']);
        Route::patch('applicant-applications/{applicantApplication}/documents/{type}', [ApplicantApplicationController::class, 'updateDocument']);
        Route::apiResource('applicant-applications', ApplicantApplicationController::class);
        Route::get('curricula/export', [CurriculumController::class, 'export']);
        Route::post('curricula/import', [CurriculumController::class, 'import']);
        Route::post('curricula/{curriculum}/items', [CurriculumController::class, 'storeItem']);
        Route::delete('curriculum-items/{curriculumItem}', [CurriculumController::class, 'destroyItem']);
        Route::apiResource('curricula', CurriculumController::class);
        Route::get('education-programs/export', [EducationProgramController::class, 'export']);
        Route::post('education-programs/import', [EducationProgramController::class, 'import']);
        Route::apiResource('education-programs', EducationProgramController::class);
        Route::get('exams/export', [ExamController::class, 'export']);
        Route::post('exams/import', [ExamController::class, 'import']);
        Route::post('exams/{exam}/results', [ExamController::class, 'storeResult']);
        Route::delete('exam-results/{examResult}', [ExamController::class, 'destroyResult']);
        Route::apiResource('exams', ExamController::class);
        Route::get('groups/export', [GroupController::class, 'export']);
        Route::post('groups/import', [GroupController::class, 'import']);
        Route::apiResource('groups', GroupController::class);
        Route::get('graduates/export', [GraduateController::class, 'export']);
        Route::post('graduates/import', [GraduateController::class, 'import']);
        Route::post('graduates/{graduate}/diploma', [GraduateController::class, 'storeDiploma']);
        Route::post('graduates/{graduate}/supplement', [GraduateController::class, 'storeSupplement']);
        Route::apiResource('graduates', GraduateController::class);
        Route::post('frdo-packages/{frdoPackage}/validate', [FrdoPackageController::class, 'validatePackage']);
        Route::post('frdo-packages/{frdoPackage}/mark-exported', [FrdoPackageController::class, 'markExported']);
        Route::post('frdo-packages/{frdoPackage}/archive', [FrdoPackageController::class, 'archive']);
        Route::get('frdo-packages/{frdoPackage}/export.csv', [FrdoPackageController::class, 'exportCsv']);
        Route::get('frdo-packages/{frdoPackage}/export.json', [FrdoPackageController::class, 'exportJson']);
        Route::apiResource('frdo-packages', FrdoPackageController::class)->only(['index', 'store', 'show']);
        Route::post('fis-packages/{fisPackage}/validate', [FisPackageController::class, 'validatePackage']);
        Route::post('fis-packages/{fisPackage}/mark-exported', [FisPackageController::class, 'markExported']);
        Route::post('fis-packages/{fisPackage}/archive', [FisPackageController::class, 'archive']);
        Route::get('fis-packages/{fisPackage}/export.csv', [FisPackageController::class, 'exportCsv']);
        Route::get('fis-packages/{fisPackage}/export.json', [FisPackageController::class, 'exportJson']);
        Route::apiResource('fis-packages', FisPackageController::class)->only(['index', 'store', 'show']);
        Route::get('specialties/export', [SpecialtyController::class, 'export']);
        Route::post('specialties/import', [SpecialtyController::class, 'import']);
        Route::apiResource('specialties', SpecialtyController::class);
        Route::post('students/bulk/preview', [StudentBulkController::class, 'preview']);
        Route::post('students/bulk/apply', [StudentBulkController::class, 'apply']);
        Route::get('students/export', [StudentController::class, 'export']);
        Route::post('students/import', [StudentController::class, 'import']);
        Route::apiResource('students', StudentController::class);
        Route::get('subjects/export', [SubjectController::class, 'export']);
        Route::post('subjects/import', [SubjectController::class, 'import']);
        Route::apiResource('subjects', SubjectController::class);
        Route::get('teaching-loads/export', [TeachingLoadController::class, 'export']);
        Route::post('teaching-loads/import', [TeachingLoadController::class, 'import']);
        Route::post('teaching-loads/{teachingLoad}/items', [TeachingLoadController::class, 'storeItem']);
        Route::delete('teaching-load-items/{teachingLoadItem}', [TeachingLoadController::class, 'destroyItem']);
        Route::apiResource('teaching-loads', TeachingLoadController::class);
        Route::get('teachers/export', [TeacherController::class, 'export']);
        Route::post('teachers/import', [TeacherController::class, 'import']);
        Route::apiResource('teachers', TeacherController::class);
    });

    Route::apiResource('schedule-lessons', ScheduleLessonController::class)
        ->middleware('permission:manage_schedule');

    Route::middleware('permission:manage_journal')->group(function (): void {
        Route::apiResource('attendance', AttendanceController::class);
        Route::apiResource('grades', GradeController::class);
        Route::get('reports/attendance-by-group', [ReportController::class, 'attendanceByGroup']);
        Route::get('reports/attendance-by-group/export', [ReportController::class, 'exportAttendanceByGroup']);
        Route::get('reports/grades-by-group', [ReportController::class, 'gradesByGroup']);
        Route::get('reports/grades-by-group/export', [ReportController::class, 'exportGradesByGroup']);
    });
});
