[CmdletBinding()]
param(
    [string]$Root
)

$ErrorActionPreference = 'Stop'
if (-not $Root) { $Root = [IO.Path]::GetFullPath((Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) '..')) }
$Root = [IO.Path]::GetFullPath($Root)
$VersionPath = Join-Path $Root 'VERSION'
if (-not [IO.File]::Exists($VersionPath)) { throw "VERSION file is missing: $VersionPath" }

$Version = ([IO.File]::ReadAllText($VersionPath)).Trim()
if ($Version.Length -eq 0) { throw 'VERSION file is empty.' }
if ($Version -notmatch '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z][0-9A-Za-z.-]*)?$') {
    throw "VERSION has invalid format: $Version"
}

$GeneratedPath = Join-Path $Root 'src\CollegePortal.Gateway.Core\GatewayBuildVersion.g.cs'
$GeneratedDirectory = Split-Path -Parent $GeneratedPath
if (-not [IO.Directory]::Exists($GeneratedDirectory)) { [IO.Directory]::CreateDirectory($GeneratedDirectory) | Out-Null }

$Lines = @(
    '// <auto-generated />',
    ('[assembly: System.Reflection.AssemblyInformationalVersion("' + $Version + '")]'),
    'namespace CollegePortal.Gateway',
    '{',
    '    internal static class GatewayBuildVersion',
    '    {',
    ('        public const string Value = "' + $Version + '";'),
    '    }',
    '}'
)
[IO.File]::WriteAllLines($GeneratedPath, [string[]]$Lines, (New-Object Text.UTF8Encoding($false)))
Write-Host "[OK] Gateway build version generated: $Version"
