<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Http\Resources\DigitalIdentityResource; use App\Http\Resources\EmployeeResource; use App\Models\DigitalIdentity; use App\Models\Employee; use App\Models\EmployeeAssignment; use App\Models\EmployeeStatusPeriod; use App\Services\AuditLogService; use App\Services\DigitalIdentityService; use App\Services\HrService; use App\Services\Import\EmployeeImportHandler; use App\Support\Csv\CsvExport; use App\Support\Phone; use Illuminate\Database\Eloquent\Builder; use Illuminate\Http\Request; use Illuminate\Http\Resources\Json\AnonymousResourceCollection; use Illuminate\Http\Response; use Illuminate\Validation\Rule; use Symfony\Component\HttpFoundation\StreamedResponse;
class EmployeeController extends Controller {
 public function __construct(private readonly HrService $hrService) {}
 public function index(Request $request): AnonymousResourceCollection { $q=Employee::query()->with(['person','teacher','primaryDepartment','primaryPosition','assignments.department','assignments.position','statusPeriods'])->when($request->string('status')->toString(),fn($q,$v)=>$q->where('status',$v))->when($request->integer('department_id'),fn($q,$v)=>$q->where('primary_department_id',$v))->when($request->integer('position_id'),fn($q,$v)=>$q->where('primary_position_id',$v))->when($request->string('employment_type')->toString(),fn($q,$v)=>$q->where('employment_type',$v))->when($request->has('is_teacher'),fn($q)=>$q->where('is_teacher',$request->boolean('is_teacher')))->when($request->string('working')->toString()==='active',fn($q)=>$q->whereNull('dismissed_at')->where('status','!=','dismissed'))->when($request->string('working')->toString()==='dismissed',fn($q)=>$q->where(fn($x)=>$x->whereNotNull('dismissed_at')->orWhere('status','dismissed')))->when($request->string('search')->toString(),function(Builder $q,string $s){$s=mb_strtolower($s);$q->where(fn($x)=>$x->whereRaw('lower(employee_number) like ?', ["%$s%"])->orWhereHas('person',fn($p)=>$p->whereRaw('lower(last_name) like ?', ["%$s%"])->orWhereRaw('lower(first_name) like ?', ["%$s%"])->orWhereRaw('lower(middle_name) like ?', ["%$s%"]))); })->orderBy('employee_number'); return EmployeeResource::collection($q->paginate($request->integer('per_page')?:50)); }
 /**
  * Выгрузка сотрудников. Заголовки берутся у обработчика импорта, а не пишутся
  * заново: файл должен грузиться обратно тем же «Универсальным импортом», и
  * разъехаться колонки не должны. Столбец «Создать учетную запись» выгружается
  * пустым намеренно — обратная загрузка не должна переоформлять учетки.
  */
 public function export(Request $request, EmployeeImportHandler $handler): StreamedResponse
 {
     $employees = Employee::query()->with(['person', 'primaryDepartment', 'primaryPosition'])->orderBy('employee_number')->get();

     return CsvExport::download('employees-'.now()->format('Ymd-His').'.csv', $handler->templateHeaders(), function (callable $row) use ($employees): void {
         foreach ($employees as $employee) {
             $row([
                 $employee->employee_number,
                 $employee->person?->last_name,
                 $employee->person?->first_name,
                 $employee->person?->middle_name,
                 $employee->person?->birth_date?->format('Y-m-d'),
                 $employee->person?->snils,
                 $employee->person?->email,
                 Phone::forExport($employee->person?->phone),
                 $employee->primaryDepartment?->name,
                 $employee->primaryPosition?->name,
                 $employee->hired_at?->format('Y-m-d'),
                 $employee->status,
                 $employee->employment_type,
                 $employee->workload_rate,
                 $employee->is_teacher ? 'да' : 'нет',
                 $employee->work_schedule_code,
                 '',
             ]);
         }
     });
 }
 public function store(Request $request): EmployeeResource { abort_unless($request->user()->hasPermission('hr.employees.create'),403); $data=$this->validateEmployee($request); $employee=$this->hrService->createEmployee($data); AuditLogService::log('hr','employee_hired',$employee,null,$employee->toArray(),$request); return new EmployeeResource($employee); }
 public function show(Employee $employee): EmployeeResource { return new EmployeeResource($employee->load(['person','teacher','primaryDepartment','primaryPosition','assignments.department','assignments.position','statusPeriods'])); }
 public function update(Request $request, Employee $employee): EmployeeResource { abort_unless($request->user()->hasPermission('hr.employees.update'),403); $old=$employee->toArray(); $employee=$this->hrService->updateEmployee($employee,$this->validateEmployee($request,true)); AuditLogService::log('hr','employee_updated',$employee,$old,$employee->toArray(),$request); return new EmployeeResource($employee); }
 public function destroy(Request $request, Employee $employee): Response { abort_unless($request->user()->hasPermission('hr.employees.dismiss'),403); $old=$employee->toArray(); $employee->update(['status'=>'dismissed','dismissed_at'=>now()->toDateString()]); AuditLogService::log('hr','employee_dismissed',$employee,$old,$employee->fresh()->toArray(),$request); return response()->noContent(); }
 public function issueDigitalPass(Request $request, Employee $employee, DigitalIdentityService $digitalIdentityService): DigitalIdentityResource { $data=$request->validate(['expires_at'=>['nullable','date','after:now']]); $identity=$digitalIdentityService->issue(DigitalIdentity::ENTITY_EMPLOYEE,$employee->id,$data['expires_at']??null,$request,'hr','employee_digital_pass_issued'); return new DigitalIdentityResource($identity); }
 public function storeAssignment(Request $request, Employee $employee): EmployeeResource { abort_unless($request->user()->hasPermission('hr.assignments.manage'),403); $data=$request->validate(['department_id'=>['required','exists:departments,id'],'position_id'=>['required','exists:positions,id'],'employment_type'=>['required',Rule::in(['full_time','part_time','internal_part_time','external_part_time','contract'])],'rate'=>['required','numeric','min:0.01','max:2'],'started_at'=>['required','date'],'ended_at'=>['nullable','date','after_or_equal:started_at'],'is_primary'=>['boolean'],'order_number'=>['nullable','string','max:100'],'order_date'=>['nullable','date'],'comment'=>['nullable','string','max:2000']]); $assignment=$employee->assignments()->create($data); if($assignment->is_primary){$employee->update(['primary_department_id'=>$assignment->department_id,'primary_position_id'=>$assignment->position_id,'employment_type'=>$assignment->employment_type,'workload_rate'=>$assignment->rate]);} AuditLogService::log('hr','employee_assignment_created',$assignment,null,$assignment->toArray(),$request); return new EmployeeResource($employee->fresh()->load(['person','teacher','primaryDepartment','primaryPosition','assignments.department','assignments.position','statusPeriods'])); }
 public function updateAssignment(Request $request, EmployeeAssignment $assignment): EmployeeResource { abort_unless($request->user()->hasPermission('hr.assignments.manage'),403); $old=$assignment->toArray(); $assignment->update($request->validate(['department_id'=>['required','exists:departments,id'],'position_id'=>['required','exists:positions,id'],'employment_type'=>['required',Rule::in(['full_time','part_time','internal_part_time','external_part_time','contract'])],'rate'=>['required','numeric','min:0.01','max:2'],'started_at'=>['required','date'],'ended_at'=>['nullable','date','after_or_equal:started_at'],'is_primary'=>['boolean'],'order_number'=>['nullable','string','max:100'],'order_date'=>['nullable','date'],'comment'=>['nullable','string','max:2000']])); AuditLogService::log('hr','employee_assignment_updated',$assignment,$old,$assignment->toArray(),$request); return new EmployeeResource($assignment->employee->fresh()->load(['person','teacher','primaryDepartment','primaryPosition','assignments.department','assignments.position','statusPeriods'])); }
 public function destroyAssignment(Request $request, EmployeeAssignment $assignment): Response { abort_unless($request->user()->hasPermission('hr.assignments.manage'),403); AuditLogService::log('hr','employee_assignment_deleted',$assignment,$assignment->toArray(),null,$request); $assignment->delete(); return response()->noContent(); }
 public function storeStatusPeriod(Request $request, Employee $employee): EmployeeResource { abort_unless($request->user()->hasPermission('hr.statuses.manage'),403); $data=$this->validateStatus($request)+['created_by'=>$request->user()->id]; $period=$employee->statusPeriods()->create($data); $employee->update(['status'=>$data['status'],'dismissed_at'=>$data['status']==='dismissed'?($data['date_from']??now()->toDateString()):$employee->dismissed_at]); AuditLogService::log('hr','employee_status_period_created',$period,null,$period->toArray(),$request); return new EmployeeResource($employee->fresh()->load(['person','teacher','primaryDepartment','primaryPosition','assignments.department','assignments.position','statusPeriods'])); }
 public function updateStatusPeriod(Request $request, EmployeeStatusPeriod $period): EmployeeResource { abort_unless($request->user()->hasPermission('hr.statuses.manage'),403); $old=$period->toArray(); $period->update($this->validateStatus($request)); AuditLogService::log('hr','employee_status_period_updated',$period,$old,$period->toArray(),$request); return new EmployeeResource($period->employee->fresh()->load(['person','teacher','primaryDepartment','primaryPosition','assignments.department','assignments.position','statusPeriods'])); }
 public function destroyStatusPeriod(Request $request, EmployeeStatusPeriod $period): Response { abort_unless($request->user()->hasPermission('hr.statuses.manage'),403); AuditLogService::log('hr','employee_status_period_deleted',$period,$period->toArray(),null,$request); $period->delete(); return response()->noContent(); }
 private function validateEmployee(Request $request,bool $update=false): array { return $request->validate(['person_id'=>['nullable','exists:people,id'],'birth_date'=>['nullable','date'],'last_name'=>[$update?'nullable':'required_without:person_id','string','max:255'],'first_name'=>[$update?'nullable':'required_without:person_id','string','max:255'],'middle_name'=>['nullable','string','max:255'],'email'=>['nullable','email','max:255'],'phone'=>['nullable','string','max:50'],'snils'=>['nullable','string','max:50'],'employee_number'=>[$update?'sometimes':'nullable','string','max:100',Rule::unique('employees','employee_number')->ignore($request->route('employee')?->id)],'status'=>['nullable',Rule::in(['candidate','active','probation','vacation','sick_leave','maternity_leave','business_trip','suspended','dismissed'])],'employment_type'=>['nullable',Rule::in(['full_time','part_time','internal_part_time','external_part_time','contract'])],'work_schedule_code'=>['nullable',Rule::in(Employee::WORK_SCHEDULE_CODES)],'hired_at'=>['nullable','date'],'dismissed_at'=>['nullable','date'],'primary_department_id'=>['nullable','exists:departments,id'],'primary_position_id'=>['nullable','exists:positions,id'],'workload_rate'=>['nullable','numeric','min:0','max:2'],'is_teacher'=>['boolean'],'comment'=>['nullable','string','max:2000']]); }
 private function validateStatus(Request $request): array { return $request->validate(['status'=>['required',Rule::in(['candidate','active','probation','vacation','sick_leave','maternity_leave','business_trip','suspended','dismissed'])],'date_from'=>['required','date'],'date_to'=>['nullable','date','after_or_equal:date_from'],'reason'=>['nullable','string','max:255'],'document_number'=>['nullable','string','max:100'],'document_date'=>['nullable','date'],'comment'=>['nullable','string','max:2000']]); }
}
